version: '3'
services:
  app:
    image: nginx:1.15
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx/
      - .:/var/www/html
    ports:
      - 80:80
    restart: always
    container_name: app
    depends_on:
      - php
      - postgres
      - rabbitmq
  php:
    build: ./docker/php
    restart: always
    container_name: php
    ports:
      - 8888:8888
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/html
  postgres:
    build: ./docker/postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.7.14-alpine
    container_name: rabbitmq
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
  composer:
    image: composer
    container_name: composer
    volumes:
      - .:/app
    command: install --ignore-platform-reqs --no-scripts
volumes:
  postgres_data: